### ISSUE TITLE
mean_power_spectrum_grey

### ISSUE THREAD

**Issue by f-amerehi** [rgeirhos/generalisation-humans-DNNs#5]
I would like to ask you how can I modify `mean_power_spectrum_grey.npy` file.It seems it only works for 224x224 images. 
For the default "test_image.JPEG" image as it is 256x256 I got error the following error

```
Traceback (most recent call last):
  File "code/image_manipulation.py", line 635, in <module>
    img_power_equalisation = power_equalisation(img, avg_power_spectrum)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "code/image_manipulation.py", line 203, in power_equalisation
    return equalise_power_spectrum(image, avg_power_spectrum)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "code/image_manipulation.py", line 478, in equalise_power_spectrum
    assert image.shape[:2] == avg_power_spectrum.shape, 'Image shape={} unequal \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Image shape=(256, 256) unequal             avg_spectrum shape=(224, 224)

```

 
I read `calculate_mean_power_spectrum.py` file and tried to use `get_mean_amplitude_spectrum` function but is seems the file is buggy and `calculate_amplitude_spectrum` is not defined or imported

**Comment by f-amerehi** [comment]
Hi @rgeirhos  hope that all is well. Could you please let me know how could I change `mean_power_spectrum_grey.npy` file to be able to run that code? 

Thanks!

**Comment by rgeirhos** [comment]
Hi @f-amerehi I messaged my co-author @carmete regarding this and am currently waiting for their reply.

**Comment by carmete** [comment]
Hi @f-amerehi! Thank you for trying out our code. Unfortunately, I cannot re-run the code right now, but here is my quick assessment.

- The error you are seen is expected, as the original mean power spectrum was calculated over a set of 224x224 images. As you correctly identified, you would need to run `get_mean_amplitude_spectrum` to produce a new power spectrum over your own dataset or any similar dataset of 256x256 images and obtain a new `get_mean_amplitude_spectrum.npy`

With regards to code bugs in `calculate_mean_power_spectrum.py`:

- `calculate_amplitude_spectrum` should be `get_amplitude_spectrum`

- `mean_power_spectrum = np.zeros(image1[:,:,0].shape, image1.dtype)` should instead be `mean_amplitude_spectrum = np.zeros(image1[:,:,0].shape, image1.dtype)`

Let me know, if this works and sorry for the inconvenience!

**Comment by f-amerehi** [comment]
Hi @carmete. Many thanks for the help!

**Comment by f-amerehi** [comment]
Thank you very much @rgeirhos also. I'll close off the issue.
